apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels:
    app: my-app
spec:
  template:
    labels:
      app: my-app
  container:
    - name: my-container
      image: httpd
      ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchlabels:
      app: my-app
  strategy: 
    type: RollingUpdate
